=== EricCartman598/Travel/resources/countries.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="init-data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="countries">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="country" type="country" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="country">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="language" type="xs:string" minOccurs="0"/>
      <xs:element name="cities" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="city" type="city" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="telephoneCode" type="xs:string" minOccurs="0"/>
      <xs:element name="isPolarNight" type="xs:string" minOccurs="0"/>
      <xs:element name="hotestMonth" type="xs:string" minOccurs="0"/>
      <xs:element name="averageTemperature" type="xs:string" minOccurs="0"/>

    </xs:sequence>
    <xs:attribute name="discriminator" type="discriminator"/>
  </xs:complexType>

  <xs:complexType name="city">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="population" type="xs:int"/>
      <xs:element name="isCapital" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="discriminator">
    <xs:restriction base="xs:string">
      <xs:enumeration value="COLD"/>
      <xs:enumeration value="HOT"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== EricCartman598/Travel/resources/countries_part1.xml
<init-data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="countries.xsd">
<countries>
		<country discriminator="HOT">
			<name>USA</name>
			<language>Eng</language>
			<cities>
				<city>
					<name>Vashington</name>
					<population>36574</population>
					<isCapital>true</isCapital>
				</city>
				<city>
					<name>New-York</name>
					<population>2588</population>
					<isCapital>false</isCapital>
				</city>
				<city>
					<name>Los-Angeles</name>
					<population>447433</population>
					<isCapital>false</isCapital>
				</city>
				<city>
					<name>Chicago</name>
					<population>23456</population>
					<isCapital>false</isCapital>
				</city>
			</cities>
			<hotestMonth>July</hotestMonth>
			<averageTemperature>39.6</averageTemperature>
		</country>		
	</countries>
</init-data>

=== EricCartman598/Travel/resources/countries_part2.xml
<init-data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="countries.xsd">
<countries>		
		<country discriminator="COLD">
			<name>Ukraine</name>
			<language>UA</language>
			<cities>
				<city>
					<name>Livov</name>
					<population>543</population>
					<isCapital>false</isCapital>
				</city>
				<city>
					<name>Kiev</name>
					<population>788</population>
					<isCapital>true</isCapital>
				</city>
				<city>
					<name>Odessa</name>
					<population>111</population>
					<isCapital>false</isCapital>
				</city>
			</cities>
			<telephoneCode>+380</telephoneCode>
			<isPolarNight>false</isPolarNight>
		</country>
		<country discriminator="COLD">
			<name>Russia</name>
			<language>Rus</language>
			<cities>
				<city>
					<name>Moscow</name>
					<population>500</population>
					<isCapital>true</isCapital>
				</city>
				<city>
					<name>Novosibirsk</name>
					<population>400</population>
					<isCapital>false</isCapital>
				</city>
				<city>
					<name>Omsk</name>
					<population>300</population>
					<isCapital>false</isCapital>
				</city>
				<city>
					<name>Spb</name>
					<population>200</population>
					<isCapital>false</isCapital>
				</city>
			</cities>
			<telephoneCode>+7</telephoneCode>
			<isPolarNight>true</isPolarNight>
		</country>
	</countries>
</init-data>
